# Worksheet 04

Name:  Kevin Wu
UID: U15403926

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

d - dimensional real space
p - it has to be greater than or equal to 1, it is just a parameter

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

We use the minkowski distance forumla and when p = 1 it is the Manhattan Distacne when p = 2 it is the Euclidean Distance

Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

it looks like the distance gets smaller and smaller as p increases

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

No, the Minkowski distance is not considered a valid distance function when p<1. The reason lies in the properties a distance function must satisfy, particularly the triangle inequality.

e) when would you use cosine similarity over the euclidan distance?

Euclidean distance might be preferred in scenarios where the magnitude and scale of features matter, and where the spatial distance between points in the feature space is crucial for determining similarity or dissimilarity.

f) what does the jaccard distance account for that the manhattan distance doesn't?

Jaccard distance explicitly accounts for the binary nature of features and measures dissimilarity based on the proportion of differing elements between sets.

#### Part 2

Consider the following two sentences:

In [15]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [16]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [17]:
corpus = [s1, s2]
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['Alice', 'hello', 'is', 'Bob', 'name', 'my']
[1, 1, 1, 0, 1, 1]


Let's add a new sentence to our corpus:

In [18]:
s3 = "hi my name is Claude"
corpus.append(s3)

a) What is the new union of words used to represent s1, s2, and s3?

In [19]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['Claude', 'Alice', 'hello', 'hi', 'is', 'Bob', 'name', 'my']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [20]:
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)

[0, 1, 1, 0, 1, 0, 1, 1]
[0, 0, 1, 0, 1, 1, 1, 1]
[1, 0, 0, 1, 1, 0, 1, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [21]:
def minkowski(x,y,p):
  if len(x) != len(y):
    raise RuntimeError("x and y should be the same dimension")
  res = 0
  for i in range(len(x)):
    res += (abs(x[i]-y[i]) ** p)
  return res ** (1/p)

print(minkowski([0,0], [1,1], 2))
print(minkowski([0,0], [1,1], 1))

1.4142135623730951
2.0


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [22]:

s4 = "hi Alice"
s5 = "hello Claude"
s6 = "Bob my name is Claude"
s7 = "hi Claude my name is Alice"
s8 = "hello Bob"
newWords = [s4, s5, s6, s7 ,s8]
for x in newWords:
  corpus.append(x)
  
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)
v2 = [1 if x in s2 else 0 for x in all_words]
print(v2)
v3 = [1 if x in s3 else 0 for x in all_words]
print(v3)
v4 = [1 if x in s4 else 0 for x in all_words]
print(v4)
v5 = [1 if x in s5 else 0 for x in all_words]
print(v5)
v6 = [1 if x in s6 else 0 for x in all_words]
print(v6)
v7 = [1 if x in s7 else 0 for x in all_words]
print(v7)
v8 = [1 if x in s8 else 0 for x in all_words]
print(v8)



print("This is to find the closest distance")
listV = [v1,v2,v3,v4,v5,v6,v7,v8]
lowest = float('inf')
for x in range(5):
  for y in range(5):
    if x != y and len(listV[x]) == len(listV[y]):
      temp = minkowski(listV[x], listV[y], 1)
      if temp < lowest:
        lowest = temp
        result = [x+1, y+1]
print(result, lowest)  





['Claude', 'Alice', 'hello', 'hi', 'is', 'Bob', 'name', 'my']
[0, 1, 1, 0, 1, 0, 1, 1]
[0, 0, 1, 0, 1, 1, 1, 1]
[1, 0, 0, 1, 1, 0, 1, 1]
[0, 1, 0, 1, 0, 0, 0, 0]
[1, 0, 1, 0, 0, 0, 0, 0]
[1, 0, 0, 0, 1, 1, 1, 1]
[1, 1, 0, 1, 1, 0, 1, 1]
[0, 0, 1, 0, 0, 1, 0, 0]
This is to find the closest distance
[1, 2] 2.0


e) How many rows and columns does this matrix have?

In [23]:
8 rows and 8 columns

SyntaxError: invalid syntax (1700638966.py, line 1)

f) When using the Manhattan distance, which two sentences are the most similar?

In [ ]:
 "hello my name is Alice"  
 "hello my name is Bob"

#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.

In [ ]:
import numpy as np

def pairwise_graph_distances(graphs):
    n = len(graphs)
    distances = np.zeros((n, n), dtype=int)

    for i in range(n):
        for j in range(i+1, n):
            edges_in_G_not_in_G_prime = np.sum(np.logical_and(graphs[i] == 1, graphs[j] == 0))
            
            edges_in_G_prime_not_in_G = np.sum(np.logical_and(graphs[i] == 0, graphs[j] == 1))
            
            distance = edges_in_G_not_in_G_prime + edges_in_G_prime_not_in_G
            
            distances[i, j] = distance
            distances[j, i] = distance

    return distances



[[0 2 4]
 [2 0 2]
 [4 2 0]]
